
spring :
    datasource :
        url : jdbc:mysql://localhost:3306/local_hibernate
        username : tester
        password : 1234
    jpa :
        properties :
            hibernate :
                format_sql : true
        show-sql : true        
        hibernate :
            ddl-auto : update    

bamdule.logging.dir : D://logs/spring-boot-log/bamdule
bamdule.logging.level : DEBUG